name: Update Dynamic README

on:
  schedule:
    - cron: "0 3,15 * * *"   # 每天 03:00 和 15:00 UTC 刷新
  workflow_dispatch: {}       # 手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser

      - name: Run updater script
        env:
          GITHUB_USERNAME: YOUR_USERNAME
          BLOG_RSS: https://your.site/rss.xml
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # 可选
        run: python scripts/update_readme.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" || git commit -m "chore: update dynamic sections"
          git push

